In [6]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

In [75]:
df = pd.read_csv("wells_info_with_prod.csv")

df['PermitDate'] = pd.to_datetime(df['PermitDate'])
df['CompletionDate'] = pd.to_datetime(df['CompletionDate'])
df['FirstProductionDate'] = pd.to_datetime(df['FirstProductionDate'])
df['SpudDate'] = pd.to_datetime(df['SpudDate'])

df['PermitDate'] = df['PermitDate'].dt.day_of_year
df['CompletionDate'] = df['CompletionDate'].dt.day_of_year
df['FirstProductionDate'] = df['FirstProductionDate'].dt.day_of_year
df['SpudDate'] = df['SpudDate'].dt.day_of_year

df['formation'] = df['formation'].astype('category').cat.codes

display(df.head())

,API,PermitDate,SpudDate,CompletionDate,FirstProductionDate,operatorNameIHS,formation,BasinName,StateName,CountyName,LatWGS84,LonWGS84,BottomHoleLatitude,BottomHoleLongitude,LATERAL_LENGTH_BLEND,PROP_PER_FOOT,WATER_PER_FOOT,Prod1Year,ProdAll
0,5005072170100,126,126,336,305,BURLINGTON RESOURCES O&G CO LP,3,DENVER BASIN,COLORADO,ARAPAHOE,39.684606,-104.642128,39.68445,-104.60557,9005.0,994.6866,591.8004,126898,201325
1,5123377130000,202,279,57,32,SRC ENERGY INCORPORATED,3,DENVER BASIN,COLORADO,WELD,40.509320,-104.780980,40.49692,-104.77859,4195.0,991.5857,628.6321,22616,34625
2,5123379280000,251,268,250,305,BONANZA CREEK ENERGY OPERATING CO LLC,3,DENVER BASIN,COLORADO,WELD,40.335390,-104.363000,40.34780,-104.36863,4273.0,1000.2760,564.4841,47523,69009
3,5123379400000,254,339,90,60,NOBLE ENERGY INCORPORATED,3,DENVER BASIN,COLORADO,WELD,40.152220,-104.530780,40.17445,-104.52932,7078.0,973.4437,824.0020,59474,81048
4,5123385820100,7,13,113,91,GREAT WESTERN OPERATING COMPANY LLC,3,DENVER BASIN,COLORADO,WELD,40.508303,-104.868180,40.49558,-104.86757,3211.0,783.5919,603.1414,14427,18050

In [77]:
vect = CountVectorizer(ngram_range=(1, 1))
df_no_prod = df.drop(columns=['Prod1Year'])
res = vect.fit_transform(df_no_prod).toarray()
print(res)
print(vect.vocabulary_)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]]
{'api': 0, 'permitdate': 12, 'spuddate': 15, 'completiondate': 4, 'firstproductiondate': 6, 'operatornameihs': 11, 'formation': 7, 'basinname': 1, 'statename': 16, 'countyname': 5, 'latwgs84': 9, 'lonwgs84': 10, 'bottomholelatitude': 2, 'bottomholelongitude': 3, 'lateral_length_blend': 8, 'prop_per_foot': 14, 'water_per_foot': 17, 'prodall': 13}

In [78]:
from sklearn.model_selection import train_test_split

df = df.select_dtypes(exclude=['object'])

X_train, X_test, y_train, y_test = train_test_split(df, df, test_size=0.2, random_state=1)

In [79]:
df.dtypes

API                       int64
PermitDate                int32
SpudDate                  int32
CompletionDate            int32
FirstProductionDate       int32
formation                  int8
LatWGS84                float64
LonWGS84                float64
BottomHoleLatitude      float64
BottomHoleLongitude     float64
LATERAL_LENGTH_BLEND    float64
PROP_PER_FOOT           float64
WATER_PER_FOOT          float64
Prod1Year                 int64
ProdAll                   int64
dtype: object

In [80]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)
print(X_train_scaled[:2])
print(X_test_scaled[:2])

[[ 0.36593993 -0.0356373   0.45456655 -0.25535342 -0.93114297  0.62068966
   1.0575864   0.12872414  1.05436111  0.12668779  0.95729218 -0.87635619
  -0.74352578 -0.34722838 -0.46000231]
 [ 1.01558202 -0.76934639 -0.340001    0.54746227  0.48465703  1.31034483
  -1.60803281  1.25552386 -1.60558461  1.25344292  0.28734263  1.15592088
   0.3671374  -0.33168823 -0.64227059]]
[[ 0.12425362  0.92561362 -1.26235469  0.02347565 -0.10245844  0.10470072
   1.33198094 -0.1651561   1.3281907  -0.16573542  0.98109646 -1.69358792
  -1.54382693  1.061825    0.98049572]
 [ 0.26711923 -1.61410646 -0.88928767 -0.71433042 -0.42264105  1.50071035
  -0.41948195  2.40711846 -0.41965189  2.40668883 -1.23287485  0.87976911
   1.66335442 -1.28598152 -1.19422007]]

In [81]:
y_train_scaled = scaler.fit_transform(y_train)
y_test_scaled = scaler.fit_transform(y_test)
print(y_train_scaled[:2])
print(y_test_scaled[:2])

[[ 0.36593993 -0.0356373   0.45456655 -0.25535342 -0.93114297  0.62068966
   1.0575864   0.12872414  1.05436111  0.12668779  0.95729218 -0.87635619
  -0.74352578 -0.34722838 -0.46000231]
 [ 1.01558202 -0.76934639 -0.340001    0.54746227  0.48465703  1.31034483
  -1.60803281  1.25552386 -1.60558461  1.25344292  0.28734263  1.15592088
   0.3671374  -0.33168823 -0.64227059]]
[[ 0.12425362  0.92561362 -1.26235469  0.02347565 -0.10245844  0.10470072
   1.33198094 -0.1651561   1.3281907  -0.16573542  0.98109646 -1.69358792
  -1.54382693  1.061825    0.98049572]
 [ 0.26711923 -1.61410646 -0.88928767 -0.71433042 -0.42264105  1.50071035
  -0.41948195  2.40711846 -0.41965189  2.40668883 -1.23287485  0.87976911
   1.66335442 -1.28598152 -1.19422007]]